### ISSUE TITLE
Failed to load dynamic library 'libiris_method_channel.so': dlopen failed: library "libiris_method_channel.so" not found

### ISSUE THREAD

**Issue by SpLokhande07** [AgoraIO-Extensions/iris_method_channel_flutter#100]
```
Unhandled exception:
E/flutter ( 3599): Invalid argument(s): Failed to load dynamic library 'libiris_method_channel.so': dlopen failed: library "libiris_method_channel.so" not found
E/flutter ( 3599): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 3599): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 3599): #2      _loadLib (package:iris_method_channel/src/platform/io/iris_event_io.dart:16:31)
E/flutter ( 3599): #3      new IrisEventIO (package:iris_method_channel/src/platform/io/iris_event_io.dart:26:54)
E/flutter ( 3599): #4      IrisMethodChannelInternalIO._execute (package:iris_method_channel/src/platform/io/iris_method_channel_internal_io.dart:421:64)
E/flutter ( 3599): #5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
E/flutter ( 3599): #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```
While initialising agora engine getting this issue. 
iris_method_channel: 2.0.1
agora_rtc_engine: 6.3.0

**Comment by littleGnAl** [comment]
Hello @SpLokhande07 , can you report this issue to the https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK repo, and fill in more details about it?  Thank you so much.
